[package]
name = "monzo2discord"
version = "0.1.0"
authors = ["Aatif Syed <aatif@aatifsyed.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
oauth2 = "3.0.0"
reqwest = "0.11.2"
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", branch = "master" }
serde = "1.0.124"
serde_yaml = "0.8.17"
thiserror = "1.0.24"
warp = "0.3.0"
